### ISSUE TITLE
Multi-FASTA file

### ISSUE THREAD

**Issue by maesaar** [metebalci/fasta2png#7]
When using fasta2png with multi-FASTA files it only takes the first contig - is this expected behaviour?

**Comment by metebalci** [comment]
No I dont think so. I didnt check with multi FASTA  files, can you share an
example ? With these files, does it make sense to combine all contigs or
provide an option to select a contig or multiple/all contigs ?

**Comment by maesaar** [comment]
Here is the example of C. jejuni genome [multi-FASTA file](https://pubmlst.org/bigsdb?db=pubmlst_campylobacter_isolates&page=plugin&name=Contigs&format=text&isolate_id=1825&match=1&pc_untagged=0&min_length=&header=1) from pubMLST database. It has 31 contigs.

It would be great if there would be an option:
1) to save different contigs to different *.png files and
2) to combine all contigs to one *.png file.

**Comment by metebalci** [comment]
Both should be possible now with v8

**Comment by maesaar** [comment]
Great job - thank you!
